services:
  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=votacao_Db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    volumes:
      - ../postgresData:/data/postgres
    ports:
      - '5432'
    restart: unless-stopped

    pgadmin:
      container_name: pgAdmin_docker_compose_support
      image: dpage/pgadmin4:latest
      environment:
        PGADMIN_DEFAULT_EMAIL: contatodmsotolani@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 5050
        PGADMIN_CONFIG_SERVER_MODE: "False"
        PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      volumes:
        - ../pgadmin:/var/lib/pgadmin
        - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
      ports:
        - '5050:5050'
      entrypoint:
        - "/bin/sh"
        - "-c"
        - "/bin/echo 'postgres:5432:*:admin:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
        -
  volumes:
    postgres:
    pgadmin: